### ISSUE TITLE
✨ [Feature] dealer_game 싱글플레이 구현

### ISSUE THREAD

**Issue by geonwule** [geonwule/dealer_game#1]
### Description

- dealer_game 싱글플레이 구현

### Todo
- [x] 📝  [Docs] Server/Client 폴더 및 Makefile 초기구성
- [x] ✨ [Feature] dealer, player, item 객체구현
- [ ] ✨ [Feature] main 게임 로직 구현
- [ ] Round
    - 탄창 : 공포탄/실탄 구성
    - 
- [ ] Item구성
    - 포션(portion) : hp 1회복
    - 돋보기(readingGlasses) : 탄창 확인
    - 커터칼(cutterKnife) : 공격 두배
    - 수갑(handcuffs) : 상대 1턴 넘기기
